version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment: 
      - PORT=3000
    depends_on: 
      - mongo #To ensure that the mongo db container always starts before the app instance

  mongo: 
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=abiola
      - MONGO_INITDB_ROOT_PASSWORD=mypassword  #
    volumes:
      - mongo-db:/data/db #named mount

  redis:
    image: redis

volumes:
  mongo-db: