version: "3"
#in docker services represnt all of our containers
services:
    nginx:
    ports:
      - "80:80"
  
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: production
    environment: 
      - NODE_ENV=production
    command: node index.js