version: "3"
#in docker services represnt all of our containers
services:
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:    
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=abiola
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret

    command: npm run dev #going to run the script in our index.js file

  mongo: 
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=abiola
      - MONGO_INITDB_ROOT_PASSWORD=mypassword



