version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build: .

    environment: 
      - PORT=3000
    depends_on: 
      - mongo #To ensure that the mongo db container always starts before the app instance

  mongo: 
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=abiola
      - MONGO_INITDB_ROOT_PASSWORD=mypassword  #
    volumes:
      - mongo-db:/data/db #named mount

  redis:
    image: redis

volumes:
  mongo-db: